version: '3.7'

services:
  introducing:
    build:
      context: .
      dockerfile: ./docker/Dockerfile

    env_file: .env

  introducing_grpc:
    build:
      context: .
      dockerfile: ./docker/Dockerfile

    env_file: .env
    command: bash /entry/grpc.sh

  introducing_react:
    build:
      context: ./frontend/introduction_frontend
      dockerfile: ./Dockerfile

networks:
  default:
      external:
          name: sharpnet