version: '3.7'

services:
  introducing:
    build:
      context: .
      dockerfile: ./docker/back.Dockerfile

    env_file: .env

    volumes:
    - "mcaq_projects:/home/coder/code-server"


volumes:
  mcaq_projects:
    external: True

networks:
  default:
      external:
          name: sharpnet