version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.12

    steps:
      - checkout

      - python/install-packages:
          pkg-manager: poetry

      - run:
          name: Run tests
          command: |
            poetry add --dev pytest
            pytest

workflows:
  sample:
    jobs:
      - build-and-test
