# pull official base image
FROM node:14-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent

# add app
COPY . ./

COPY ./sharpnet/nginx.conf /sharpnet/nginx.conf

RUN npm run build

# start app
CMD ["npm", "run", "prod"]