"""
https://www.goodhousekeeping.com/life/parenting/a31401884/gender-neutral-baby-names/
"""

MIN_BACKSTORY_LENGTH = 170

TENSES = [
    (" yours ", " theirs "),
    (" your ", " their "),
    ("Your ", "Their "),
    (" you ", " they "),
    ("You ", "They "),
    ("theynger", "younger")
]


NAMES = [
    "Bellamy",
    "Charlie",
    "Dakota",
    "Denver",
    "Emerson",
    "Finley",
    "Justice",
    "River",
    "Skyler",
    "Tatum",
    "Jessie",
    "Marion",
    "Jackie",
    "Alva",
    "Ollie",
    "Jodie",
    "Cleo",
    "Kerry",
    "Frankie",
    "Guadalupe",
    "Carey",
    "Tommie",
    "Angel",
    "Hollis",
    "Sammie",
    "Jamie",
    "Kris",
    "Robbie",
    "Tracy",
    "Merrill",
    "Noel",
    "Rene",
    "Johnnie",
    "Ariel",
    "Jan",
    "Casey",
    "Jackie",
    "Kerry",
    "Jodie",
    "Finley",
    "Skylar",
    "Justice",
    "Rene",
    "Darian",
    "Frankie",
    "Oakley",
    "Robbie",
    "Remy",
    "Milan",
    "Jaylin",
    "Devan",
    "Armani",
    "Charlie",
    "Stevie",
    "Channing",
    "Gerry",
    "Monroe",
    "Kirby",
    "Azariah",
    "Santana",
]